"""Walk ``~/.autoresearchclaw/specimens/`` and emit a pilot manifest.

The eval-pilot orchestrator (``.github/scripts/eval_project358382_pilot.py``)
already accepts ``--specimens-manifest`` as a way to pin a fixed list
of (CT, mesh) pairs without going through the MorphoSource discovery
API. This module produces such a manifest from whatever's in the
local cache.

Cache layout (per ``slicer_tool.py``)
-------------------------------------
::

    ~/.autoresearchclaw/specimens/
      media_<media_id>/
        morphosource_media-id-<media_id>_download-<hash>.zip   # optional
        morphosource_media-id-<media_id>_download-<hash>/      # extracted
          <subfolder>/
            <files>.{ply,stl,obj,nii.gz,zip,...}
        analysis/
          analysis.json   # produced by the SlicerMorph layer-1 step

Reality check
-------------
At the time of writing, every cached specimen on this machine is
**mesh-only** (PLY/STL/OBJ). The cache has no DICOM, TIFF or NIfTI
volumes. So the cached manifest can supply the ``mesh_media_id`` half
of a pair, but the matching CT half has to come from somewhere else
(e.g. a tiny synthetic NIfTI generated by ``synthetic.py`` for
replay tests, or a one-time live download for the recording session).

This module surfaces every cached media as a ``CachedSpecimen`` and
the higher-level test fixtures decide how to combine them.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, asdict, field
from pathlib import Path
from typing import Iterable, Optional


_MEDIA_DIR_RE = re.compile(r"^media_(\d+)$")
_MESH_EXTS = {".ply", ".stl", ".obj"}
_VOLUME_EXTS = {".nii", ".nii.gz", ".nrrd", ".mha", ".mhd"}
_DICOM_EXTS = {".dcm"}
_TIFF_EXTS = {".tif", ".tiff"}


@dataclass
class CachedSpecimen:
    """One cached MorphoSource media directory."""

    media_id: str
    media_dir: Path
    has_zip: bool
    has_extracted: bool
    extracted_dirs: list[Path] = field(default_factory=list)
    mesh_files: list[Path] = field(default_factory=list)
    volume_files: list[Path] = field(default_factory=list)
    dicom_dirs: list[Path] = field(default_factory=list)
    tiff_dirs: list[Path] = field(default_factory=list)
    inner_zip_files: list[Path] = field(default_factory=list)
    analysis: Optional[dict] = None
    bytes_on_disk: int = 0

    @property
    def kind(self) -> str:
        """Best guess at this specimen's media kind."""
        if self.volume_files or self.dicom_dirs or self.tiff_dirs:
            return "ct"
        if self.mesh_files:
            return "mesh"
        if self.inner_zip_files:
            return "zipped"
        return "unknown"

    @property
    def primary_mesh(self) -> Optional[Path]:
        if not self.mesh_files:
            return None
        return max(self.mesh_files, key=lambda p: p.stat().st_size if p.exists() else 0)

    @property
    def primary_volume(self) -> Optional[Path]:
        if self.volume_files:
            return self.volume_files[0]
        if self.dicom_dirs:
            return self.dicom_dirs[0]
        if self.tiff_dirs:
            return self.tiff_dirs[0]
        return None

    @property
    def taxonomy_hint(self) -> str:
        """Best-effort genus inferred from a mesh filename.

        Names look like ``USNM_276657_Ateles_humR_smooth-000040409.ply``
        or ``Macaca-fascicularis-fascicularis-f-MCZ-35937-cranium-...``.
        We grab the first capitalised token that isn't an obvious
        institution code.
        """
        if not self.mesh_files:
            return ""
        stem = self.mesh_files[0].stem
        # Split on common delimiters; first plausible genus wins.
        parts = re.split(r"[-_\s]+", stem)
        skip = {"usnm", "amnh", "mcz", "cmnh", "fmnh", "ku", "mb",
                "ms", "media", "morphosource", "smooth", "cropped",
                "model", "mesh", "skull", "cranium", "mandible",
                "left", "right", "lateral", "dorsal"}
        for tok in parts:
            t = tok.lower()
            if not tok or not tok[0].isalpha():
                continue
            if t in skip:
                continue
            if len(tok) <= 2:
                continue
            if tok[0].isupper() or tok[0].islower():
                # Accept the first genus-like token.
                return tok
        return ""

    def to_manifest_entry(
        self,
        *,
        ct_media_id: Optional[str] = None,
        physical_object_id: Optional[str] = None,
        taxonomy: Optional[str] = None,
        project_query: str = "Colors of Skull Anatomy",
        ct_local_dir: Optional[Path] = None,
        mesh_local_dir: Optional[Path] = None,
    ) -> dict:
        """Render a row compatible with ``SpecimenPair`` JSON.

        ``ct_media_id`` defaults to ``media_id`` (single-media row,
        useful when the caller plans to plug in a synthetic CT).
        """
        ct_id = ct_media_id or self.media_id
        po_id = physical_object_id or f"local_obj_{self.media_id}"
        return {
            "physical_object_id": po_id,
            "physical_object_title": f"cached-{self.media_id}",
            "taxonomy": taxonomy or self.taxonomy_hint or "Unknown",
            "ct_media_id": ct_id,
            "ct_title": f"synthetic_or_local_ct_for_{ct_id}",
            "ct_media_type": "ct image series",
            "ct_file_size": None,
            "mesh_media_id": self.media_id,
            "mesh_title": (self.primary_mesh.name if self.primary_mesh else ""),
            "mesh_media_type": "mesh",
            "mesh_file_size": (
                self.primary_mesh.stat().st_size
                if self.primary_mesh and self.primary_mesh.exists()
                else None
            ),
            "project_query": project_query,
            # extra (non-SpecimenPair) hints for the orchestrator's
            # offline mode — ignored by the dataclass constructor.
            "_local_mesh_path": (
                str(self.primary_mesh) if self.primary_mesh else None
            ),
            "_local_volume_path": (
                str(self.primary_volume) if self.primary_volume else None
            ),
            "_ct_local_dir": str(ct_local_dir) if ct_local_dir else None,
            "_mesh_local_dir": str(mesh_local_dir or self.media_dir),
            "_kind": self.kind,
            "_bytes_on_disk": self.bytes_on_disk,
        }

    def to_summary_dict(self) -> dict:
        return {
            "media_id": self.media_id,
            "media_dir": str(self.media_dir),
            "kind": self.kind,
            "has_zip": self.has_zip,
            "has_extracted": self.has_extracted,
            "n_mesh_files": len(self.mesh_files),
            "n_volume_files": len(self.volume_files),
            "n_dicom_dirs": len(self.dicom_dirs),
            "n_tiff_dirs": len(self.tiff_dirs),
            "n_inner_zips": len(self.inner_zip_files),
            "primary_mesh": (
                str(self.primary_mesh) if self.primary_mesh else None
            ),
            "taxonomy_hint": self.taxonomy_hint,
            "bytes_on_disk": self.bytes_on_disk,
            "has_analysis": self.analysis is not None,
        }


def _classify_files(extracted_dir: Path) -> tuple[list[Path], list[Path], list[Path], list[Path], list[Path]]:
    """Return (meshes, volumes, dicom_dirs, tiff_dirs, inner_zips)."""
    meshes: list[Path] = []
    volumes: list[Path] = []
    dicom_dirs: set[Path] = set()
    tiff_dirs: set[Path] = set()
    inner_zips: list[Path] = []
    if not extracted_dir.is_dir():
        return [], [], [], [], []
    for p in extracted_dir.rglob("*"):
        if p.is_dir():
            continue
        # Compose double-extension for nii.gz handling.
        suffixes = [s.lower() for s in p.suffixes]
        suf = suffixes[-1] if suffixes else ""
        suf2 = "".join(suffixes[-2:]) if len(suffixes) >= 2 else ""
        if suf in _MESH_EXTS:
            meshes.append(p)
        elif suf2 == ".nii.gz" or suf in {".nii", ".nrrd", ".mha", ".mhd"}:
            volumes.append(p)
        elif suf in _DICOM_EXTS:
            dicom_dirs.add(p.parent)
        elif suf in _TIFF_EXTS:
            tiff_dirs.add(p.parent)
        elif suf == ".zip":
            inner_zips.append(p)
    return (
        sorted(meshes),
        sorted(volumes),
        sorted(dicom_dirs),
        sorted(tiff_dirs),
        sorted(inner_zips),
    )


def _dir_size(p: Path) -> int:
    total = 0
    for sub in p.rglob("*"):
        try:
            if sub.is_file():
                total += sub.stat().st_size
        except OSError:
            pass
    return total


def scan_specimen_dir(media_dir: Path) -> Optional[CachedSpecimen]:
    """Inspect a single ``media_<id>`` directory."""
    m = _MEDIA_DIR_RE.match(media_dir.name)
    if not m:
        return None
    media_id = m.group(1)

    zips = list(media_dir.glob("morphosource_media-id-*.zip"))
    extracted = sorted(
        d for d in media_dir.glob("morphosource_media-id-*")
        if d.is_dir()
    )

    meshes: list[Path] = []
    volumes: list[Path] = []
    dicom_dirs: list[Path] = []
    tiff_dirs: list[Path] = []
    inner_zips: list[Path] = []
    for ed in extracted:
        m_, v_, dcm_, tif_, iz_ = _classify_files(ed)
        meshes.extend(m_)
        volumes.extend(v_)
        dicom_dirs.extend(dcm_)
        tiff_dirs.extend(tif_)
        inner_zips.extend(iz_)

    analysis = None
    apath = media_dir / "analysis" / "analysis.json"
    if apath.exists():
        try:
            analysis = json.loads(apath.read_text())
        except Exception:
            analysis = None

    return CachedSpecimen(
        media_id=media_id,
        media_dir=media_dir,
        has_zip=bool(zips),
        has_extracted=bool(extracted),
        extracted_dirs=extracted,
        mesh_files=meshes,
        volume_files=volumes,
        dicom_dirs=dicom_dirs,
        tiff_dirs=tiff_dirs,
        inner_zip_files=inner_zips,
        analysis=analysis,
        bytes_on_disk=_dir_size(media_dir),
    )


def scan_specimens(root: os.PathLike | str) -> list[CachedSpecimen]:
    """Scan ``root`` for ``media_*`` subdirectories.

    Returns specimens sorted by ``media_id`` for stable manifest output.
    """
    root_p = Path(root).expanduser()
    if not root_p.is_dir():
        return []
    out: list[CachedSpecimen] = []
    for sub in sorted(root_p.iterdir()):
        if not sub.is_dir():
            continue
        spec = scan_specimen_dir(sub)
        if spec is not None:
            out.append(spec)
    return out


def filter_skull_meshes(specs: Iterable[CachedSpecimen]) -> list[CachedSpecimen]:
    """Return cached specimens that look like skulls / crania.

    Heuristic: the primary mesh's filename or one of its parent
    directory names mentions ``skull`` or ``crani`` (cranium /
    cranial). Filename-only — the per-specimen ``analysis.json`` is
    *not* a useful signal here because the SlicerMorph layer-1 step
    always writes ``distances.skull_*`` keys regardless of element.
    """
    out: list[CachedSpecimen] = []
    for s in specs:
        if not s.mesh_files:
            continue
        candidates: list[str] = []
        for p in s.mesh_files:
            candidates.append(p.name.lower())
            candidates.extend(part.lower() for part in p.parts[-4:])
        joined = " ".join(candidates)
        # Reject "postcrani(al)" before checking the positive "crani" /
        # "skull" cues; otherwise non-skull elements like
        # "Misc Postcranials Mesh Etc" sneak in.
        normalised = joined.replace("postcrani", "")
        if "skull" in normalised or "crani" in normalised:
            out.append(s)
    return out


def write_manifest(
    out_path: os.PathLike | str,
    specs: Iterable[CachedSpecimen],
    *,
    project_query: str = "Colors of Skull Anatomy",
    ct_provider: str = "synthetic",
    pretty: bool = True,
) -> Path:
    """Write a JSON manifest of cached specimens.

    The format is a list of dicts where each dict is compatible with
    ``SpecimenPair`` plus a few ``_local_*`` extras.
    """
    rows: list[dict] = []
    for s in specs:
        # When we don't have a local CT, use a synthetic placeholder
        # ID so the orchestrator's run_id slug stays stable.
        ct_id = (
            s.media_id
            if s.kind == "ct"
            else f"synthetic_ct_for_{s.media_id}"
        )
        rows.append(s.to_manifest_entry(
            ct_media_id=ct_id,
            project_query=project_query,
        ))
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    if pretty:
        out.write_text(json.dumps(
            {"ct_provider": ct_provider, "specimens": rows}, indent=2
        ))
    else:
        out.write_text(json.dumps(
            {"ct_provider": ct_provider, "specimens": rows}
        ))
    return out


# ---------------------------------------------------------------------------
# CLI: python -m metadata_to_morphsource.jetstream_replay.cache_index
# ---------------------------------------------------------------------------


def _main(argv: Optional[list[str]] = None) -> int:
    import argparse

    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--root",
        type=Path,
        default=Path.home() / ".autoresearchclaw" / "specimens",
    )
    p.add_argument("--out", type=Path, default=None)
    p.add_argument(
        "--filter",
        choices=("all", "mesh", "ct", "skull"),
        default="all",
    )
    p.add_argument("--project-query", default="Colors of Skull Anatomy")
    p.add_argument("--summary", action="store_true",
                   help="Print a one-line per-specimen summary instead of "
                        "writing a manifest")
    args = p.parse_args(argv)

    specs = scan_specimens(args.root)
    if args.filter == "mesh":
        specs = [s for s in specs if s.kind == "mesh"]
    elif args.filter == "ct":
        specs = [s for s in specs if s.kind == "ct"]
    elif args.filter == "skull":
        specs = filter_skull_meshes(specs)

    if args.summary:
        for s in specs:
            print(json.dumps(s.to_summary_dict()))
        return 0

    if args.out is None:
        print(json.dumps(
            {"specimens": [s.to_manifest_entry(project_query=args.project_query)
                           for s in specs]},
            indent=2,
        ))
        return 0

    write_manifest(args.out, specs, project_query=args.project_query)
    print(f"Wrote {len(specs)} specimens to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
