name: Morphosource Data Comparison and Verification

on:
  workflow_dispatch:
    inputs:
      csv_filename:
        description: 'CSV file to compare against (filename only, not full path)'
        required: true
        default: 'UF Lepidosaura All CT Scan List Compare.csv'

jobs:
  compare_and_verify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy fuzzywuzzy python-Levenshtein matplotlib seaborn ipywidgets requests
      
      - name: Create output directory
        run: mkdir -p data/output
      
      - name: Run comparison script
        run: |
          echo "Running comparison with ${{ github.event.inputs.csv_filename }}"
          python compare.py << EOF
          data/json/morphosource_data_complete_compare.json
          data/csv/${{ github.event.inputs.csv_filename }}
          data/output/matched.csv
          n
          EOF
        shell: bash
      
      - name: Run verification script
        env:
          MORPHOSOURCE_API_KEY: ${{ secrets.MORPHOSOURCE_API_KEY }}
        run: |
          echo "Running verification on matched data"
          python verify_pixel_spacing.py --csv data/output/matched.csv --output data/output/confirmed_matches.csv --api-key "$MORPHOSOURCE_API_KEY"
      
      - name: List output files
        run: |
          ls -la data/output/
      
      - name: Upload result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: morphosource-comparison-results
          path: |
            data/output/matched.csv
            data/output/confirmed_matches.csv
